version: '3.9'
services:
    db:
        image: bitnami/postgresql
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_DB=${DB_NAME}
        container_name: db
        volumes:
            - pgdata:/bitnami/postgresql

    webserver:
        build: .
        ports:
            - '8080:8080'
            - '9990:9990'
        environment:
            - DATASOURCE_JNDI
            - DATASOURCE_NAME
            - DB_USER
            - DB_PASS
            - DB_HOST
            - DB_PORT
            - DB_NAME
            - WILDFLY_ADMIN_PASSWORD
            - POSTGRES_DRIVER_VERSION
        container_name: webserver
        depends_on:
            - db
volumes:
    pgdata:
