
##### Get Order Details
GET http://localhost:8080/pref/api/orders/1
Accept: application/json

##### Get Packages
GET http://localhost:8080/pref/api/packages
Accept: application/json

##### Get Package Details
GET http://localhost:8080/pref/api/packages/1
Accept: application/json
