
### Get Order Details
GET http://localhost:8080/pref/api/orders/1
Accept: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Dispatch Order Line
PATCH http://localhost:8080/pref/api/orders/1
Content-Type: application/json

{
  "orderPackageId": 21
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### List Orders
GET http://localhost:8080/pref/api/orders?offset=0&limit=10
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### List Order Packages
GET http://localhost:8080/pref/api/orderPackages
Accept: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Get Order Package
GET http://localhost:8080/pref/api/orderPackages/19
Accept: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Get Packages
GET http://localhost:8080/pref/api/packages
Accept: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

##### Get Package Details
GET http://localhost:8080/pref/api/packages/1
Accept: application/json


> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


#### Get Package Logs from Simple Package
GET http://localhost:8080/pref/api/package-logs/package/1
Accept: application/json


> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}



### Create Package Log
POST http://localhost:8080/pref/api/package-logs
Content-Type: application/json

{
  "simplePackageId": 1,
  "location": "Madrid",
  "temperature": 20,
  "humidity": 50
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### Create Package Log Error
POST http://localhost:8080/pref/api/package-logs
Content-Type: application/json

{
  "simplePackageId": 100000,
  "location": "Madrid",
  "temperature": 20,
  "humidity": 50
}

> {%
    client.test("Request not executed successfully (excepted)", function() {
        client.assert(response.status === 404, "Response status is not 404");
    });
%}

### Create Observation Log
POST http://localhost:8080/pref/api/observations
Content-Type: application/json

{
  "phenomenonType": "TEMPERATURE",
  "author": "Scan",
  "simplePackageId": 20,
  "value": 30
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### List Observations
GET http://localhost:8080/pref/api/observations
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### List Observations from Package
GET http://localhost:8080/pref/api/observations/package/20
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
