name: Azure Container Registry Build and Deploy

on:
  push:
    branches:
      - backend

env:
  IMAGE_NAME: wildfly
  ACR_SERVER: projpref.azurecr.io
  ACR_USERNAME: ${{ secrets.AzureAppService_ContainerUsername_45dacb0dc38546d4b40770bccdf0f235 }}
  ACR_PASSWORD: ${{ secrets.AzureAppService_ContainerPassword_7bdf324980c6433cb912b5a0f2722330 }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build the WAR file
      run: |
        mvn clean package
    - name: Build the Docker image
      run: |
        docker build -t $IMAGE_NAME .
    - name: Run the Docker container
      run: |
        docker run -d -p 8080:8080 -p 9990:9990 -e DATASOURCE_JNDI=$vars.DATASOURCE_JNDI -e DATASOURCE_NAME=$vars.DATASOURCE_NAME -e DB_USER=$vars.DB_USER -e DB_PASS=$vars.DB_PASS -e DB_HOST=$vars.DB_HOST -e DB_PORT=$vars.DB_PORT -e DB_NAME=$vars.DB_NAME -e POSTGRES_DRIVER_VERSION=$vars.POSTGRES_DRIVER_VERSION -e WILDFLY_ADMIN_PASSWORD=$vars.WILDFLY_ADMIN_PASSWORD --name wildfly $IMAGE_NAME
    - name: Copy the WAR file to the Docker container
      run: |
        docker cp target/pref.war wildfly:/opt/jboss/wildfly/standalone/deployments
    - name: Commit the changes to the Docker container
      run: |
        docker commit wildfly $IMAGE_NAME
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_SERVER }}
        username: ${{ env.ACR_USERNAME }}
        password: ${{ env.ACR_PASSWORD }}

    - name: Tag the Docker image
      run: |
        docker tag $IMAGE_NAME $ACR_SERVER/$IMAGE_NAME:latest
    - name: Push the Docker image to Azure Container Registry
      run: |
        docker push $ACR_SERVER/$IMAGE_NAME:latest
  deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'pref'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_0abca10091c846e1baee59ddae1a7fb5 }}
          images: ${{ env.ACR_SERVER }}/${{ env.IMAGE_NAME }}:latest
          
        env:
          DOCKER_REGISTRY_SERVER_URL: https://${{ env.ACR_SERVER }}
          DOCKER_REGISTRY_SERVER_USERNAME: ${{ env.ACR_USERNAME }}
          DOCKER_REGISTRY_SERVER_PASSWORD: ${{ env.ACR_PASSWORD }}
