# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pref

on:
  push:
    branches:
      - backend
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://projpref.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f4e1818e943e460589d4ad3ad8a6c30b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_782a1a798e3441f0bd71c637f2e660ef }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: projpref.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f4e1818e943e460589d4ad3ad8a6c30b }}/wildfly:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pref'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_46b8b03f47ef4f268bcf4856cd58a996 }}
        images: 'projpref.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f4e1818e943e460589d4ad3ad8a6c30b }}/wildfly:${{ github.sha }}'