# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pref

on:
  push:
    branches:
      - backend
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://projpref.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3ab46bedd4444fdd8f0f91ae50fd2c85 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_41453aba5acf4dc29ce0f3c0a4ec8c04 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: projpref.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3ab46bedd4444fdd8f0f91ae50fd2c85 }}/wildfly:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pref'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_780967313d304d12b9b3e99b77f724cf }}
        images: 'projpref.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3ab46bedd4444fdd8f0f91ae50fd2c85 }}/wildfly:${{ github.sha }}'